export const images = [
  { id: 1, img: 'slide-1.jpg' },
  { id: 2, img: 'slide-2.jpg' },
  { id: 3, img: 'slide-3.jpg' },
  { id: 4, img: 'slide-4.jpg' },
  { id: 5, img: 'slide-5.jpg' },
  { id: 6, img: 'slide-6.jpg' },
  { id: 7, img: 'slide-7.jpg' },
  { id: 8, img: 'slide-8.jpg' },
  { id: 9, img: 'slide-9.jpg' },
  { id: 10, img: 'slide-10.jpg' },
  { id: 11, img: 'slide-11.jpg' },
  { id: 12, img: 'slide-12.jpg' },
  { id: 13, img: 'slide-13.jpg' },
  { id: 14, img: 'slide-14.jpg' },
  { id: 15, img: 'slide-15.jpg' },
  { id: 16, img: 'slide-16.jpg' },
  { id: 17, img: 'slide-17.jpg' },
  { id: 18, img: 'slide-18.jpg' },
  { id: 19, img: 'slide-19.jpg' },
];

export const gallery = [
  { id: 1, img: 'slide-1.jpg' },
  { id: 2, img: 'slide-2.jpg' },
  { id: 3, img: 'slide-3.jpg' },
  { id: 4, img: 'img-1.jpg' },
  { id: 5, img: 'slide-4.jpg' },
  { id: 6, img: 'slide-5.jpg' },
  { id: 7, img: 'slide-6.jpg' },
  { id: 8, img: 'slide-7.jpg' },
  { id: 9, img: 'img-2.jpg' },
  { id: 10, img: 'slide-9.jpg' },
  { id: 11, img: 'slide-10.jpg' },
  { id: 12, img: 'slide-11.jpg' },
  { id: 13, img: 'slide-12.jpg' },
  { id: 14, img: 'img-3.jpg' },
  { id: 15, img: 'slide-14.jpg' },
  { id: 16, img: 'slide-15.jpg' },
  { id: 17, img: 'slide-16.jpg' },
  { id: 18, img: 'img-4.jpg' },
  { id: 19, img: 'slide-17.jpg' },
  { id: 20, img: 'slide-18.jpg' },
  { id: 21, img: 'slide-19.jpg' },
];
